### ISSUE TITLE
New `boot.initrd.secrets` for existing initrd is not written to the ESP

### ISSUE THREAD

**Issue by nikstur** [nix-community/lanzaboote#103]
Currently, the secret is always added to the initrd in the tempdir but not actually copied over to the ESP because AFAIK the secret does not change the input hash (and thus path) of the initrd in the nix store and in the ESP.

**Comment by blitz** [comment]
@nikstur Can you elaborate a bit? What secret?

**Comment by nikstur** [comment]
If you change `boot.initrd.secrets` between two generations but the initrd itself does not change, the secrets do not actually end up in the initrd on the ESP.
