### ISSUE TITLE
Potential TOCTOU while reading stub data from filesystem rather than memory

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/lanzaboote#123]
To the best of my understanding, it was analyzed in #96 that lanzastub is reading the hashes/filenames from the **filesystem**, exposing lanzastub to a nasty time of check, time of use vulnerability where an attacker with a primitive that can modify the filesystem and suspend execution of lanzastub can race for changing hashes / filenames to load attacker-controlled files which will bypass SecureBoot model because lanzastub being already executed means that firmware has validated its signature and is allowed to do anything now.

The fix is quite easy: rather than reading from the filesystem, we should read our own binary memory and extract the relevant sections from there.

cc @blitz

Reported-By: @govanify

**Comment by blitz** [comment]
This is indeed an issue when the attacker is able to modify the ESP on the fly (i.e. malicious storage controller). I'll look into it when I have some time.

That being said: What's the attacker model of Secure Boot? Is the Secure Boot implementation meant to be secure in the presence of such an attacker?

**Comment by GovanifY** [comment]
In theory any side bus MITM is fair game, although the specification does not define well its threat model AFAIK.
See https://edk2-docs.gitbook.io/edk-ii-secure-coding-guide/appendix_threat_model_for_edk_ii for EDK2's take on it.

But, regardless of the threat model defined, we really should aim to protect against such kinds of attacks, especially in such a simple stub. While I agree that the boot chain could technically be compromised at the UEFI level, introducing some interrupt which is then going to be triggered when the kernel tries to upload external devices firmware and overwrite it, I think it is fair game to assume that the UEFI we are using is not compromised.

This is, after all, the job of the TPM to only relinquish keys only under a safe environment.

**Comment by blitz** [comment]
@GovanifY Thanks for the link. This is really interesting.

> regardless of the threat model defined, we really should aim to protect against such kinds of attacks

Definitely.
