### ISSUE TITLE
Informative logging for malformed generations

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/lanzaboote#127]
Currently, we lost the ability to tell the users about anomalous situations (malformed generations) in info-level logging (the default).

It would be helpful to devise strategies to tell the users in an helpful way about potential problems and offers potential solutions.

**Comment by nikstur** [comment]
More specifically, we should give the user a single `log::info` message that there are (multiple) malformed generations, and that they can be handled in a certain way.
