### ISSUE TITLE
Remove hardcoding of the bootloader options

### ISSUE THREAD

**Issue by kanashimia** [nix-community/lanzaboote#133]
You should be able to configure systemd-boot options and maybe optionally ID=lanza tag.

I have arch installed with UKI and it always selected by default with this module, because of the alphabetical ordering.
To boot into the lastest nixos generation by default, you need to either modify ID to something lower than `arch`, 
or you need to modify `loader.conf`, for example like this:

```
timeout 0
console-mode keep
default nixos-*
```

You can use globbing in the configuration, multiple entries are automatically ordered as described in the [The Boot Loader Specification](https://uapi-group.org/specifications/specs/boot_loader_specification/#sorting)

**Comment by RaitoBezarius** [comment]
Good point; can you send a PR?

**Comment by kanashimia** [comment]
> Good point; can you send a PR?

Made a PR that allows to generate loader.conf from the settings option, that should be good enough. Customizing ID key as a way of ordering seems weird anyway, i don't really think it is much of a problem with it being hardcoded.
