### ISSUE TITLE
`nix-collect-garbage -d` doesn't delete old system profiles

### ISSUE THREAD

**Issue by lovesegfault** [nix-community/lanzaboote#174]
I've just set up lanzaboote, and everything worked perfectly, but once I had a secure-booted system I tried deleting old system generations, and they just won't go away.

```
$ bootctl status
System:
      Firmware: UEFI 2.70 (Lenovo 0.4720)
 Firmware Arch: x64
   Secure Boot: enabled (user)
  TPM2 Support: yes
  Boot into FW: supported
...

$ sudo nix-collect-garbage -d
finding garbage collector roots...
deleting garbage...
deleting unused links...
note: currently hard linking saves 16944.06 MiB
0 store paths deleted, 0.00 MiB freed

$ ls -l /nix/var/nix/profiles
total 88
lrwxrwxrwx 1 root root 43 Apr 19 09:24 default -> /nix/var/nix/profiles/per-user/root/profile
drwxr-xr-x 1 root root 24 Nov 18 16:58 per-user
lrwxrwxrwx 1 root root 15 May  4 15:21 system -> system-196-link
lrwxrwxrwx 1 root root 87 Apr 19 09:06 system-177-link -> /nix/store/z318czd996yxdp5i7rd2jqrdb1f8132a-nixos-system-spinoza-23.05.20230417.f00994e
lrwxrwxrwx 1 root root 87 Apr 19 09:23 system-178-link -> /nix/store/asrck6hzb4sgf7cpk6byg7ips6ss0x25-nixos-system-spinoza-23.05.20230417.f00994e
lrwxrwxrwx 1 root root 87 Apr 19 09:37 system-179-link -> /nix/store/5cgy2mmfbap5rz3gy1pqqdjqx39h2gxi-nixos-system-spinoza-23.05.20230417.f00994e
lrwxrwxrwx 1 root root 87 Apr 19 09:43 system-180-link -> /nix/store/48acxky2h6l0l6b9nihpxdd5qav5asy6-nixos-system-spinoza-23.05.20230417.f00994e
lrwxrwxrwx 1 root root 87 Apr 20 09:19 system-181-link -> /nix/store/ml9v2sp54szx6wg2ln0gsmpsbsbvbfc9-nixos-system-spinoza-23.05.20230417.f00994e
lrwxrwxrwx 1 root root 87 Apr 20 09:25 system-182-link -> /nix/store/j6ih7k6qik37hr036v5xxrhjy3syixyf-nixos-system-spinoza-23.05.20230417.f00994e
lrwxrwxrwx 1 root root 87 Apr 24 09:22 system-183-link -> /nix/store/i6p80xgqacjc5jammqqfbqn7r0bvvflf-nixos-system-spinoza-23.05.20230423.e78d25d
lrwxrwxrwx 1 root root 87 Apr 24 09:29 system-184-link -> /nix/store/c5dfx8pxbwygqsm9c8xr9vqk2s3jayvr-nixos-system-spinoza-23.05.20230423.e78d25d
lrwxrwxrwx 1 root root 87 Apr 25 10:32 system-185-link -> /nix/store/0zah3511rbqahsjr9z2axjc2i4rkb94a-nixos-system-spinoza-23.05.20230424.884ac29
lrwxrwxrwx 1 root root 87 Apr 26 09:21 system-186-link -> /nix/store/lz3k1g006q3m0rmxc3hajfvlnkzb7z93-nixos-system-spinoza-23.05.20230425.c801836
lrwxrwxrwx 1 root root 87 Apr 26 10:37 system-187-link -> /nix/store/h09xwkzbykl4qnqqf42ajzw6z2vrw81n-nixos-system-spinoza-23.05.20230425.c801836
lrwxrwxrwx 1 root root 87 Apr 27 10:50 system-188-link -> /nix/store/a04kjrhak3zim4qr3sr9dhipjb0gmsji-nixos-system-spinoza-23.05.20230426.d6b863f
lrwxrwxrwx 1 root root 87 Apr 27 15:42 system-189-link -> /nix/store/f2g2k3sbp90l9lcq8q3f8y3ilm4hfji9-nixos-system-spinoza-23.05.20230426.d6b863f
lrwxrwxrwx 1 root root 87 Apr 27 15:47 system-190-link -> /nix/store/anq61x03nvwynyh03jigw062nf5fwkpj-nixos-system-spinoza-23.05.20230426.d6b863f
lrwxrwxrwx 1 root root 87 May  2 12:15 system-191-link -> /nix/store/h1m9wrkpck8bar39f48w9702zj4y4y6y-nixos-system-spinoza-23.05.20230502.1a411f2
lrwxrwxrwx 1 root root 87 May  2 12:16 system-192-link -> /nix/store/1j7sdnk1n2drx8cwx14ygqlq6g0c5bai-nixos-system-spinoza-23.05.20230502.1a411f2
lrwxrwxrwx 1 root root 87 May  2 12:19 system-193-link -> /nix/store/724h04an77dvr2jxn17fqx1nn5d25p8j-nixos-system-spinoza-23.05.20230502.1a411f2
lrwxrwxrwx 1 root root 87 May  2 15:59 system-194-link -> /nix/store/m43yw3vfswzwdzxmml4yh66l087n20if-nixos-system-spinoza-23.05.20230502.1a411f2
lrwxrwxrwx 1 root root 87 May  4 15:11 system-195-link -> /nix/store/izgfascmh5caznwvgjanvidpfp8h4vbw-nixos-system-spinoza-23.05.20230502.1a411f2
lrwxrwxrwx 1 root root 87 May  4 15:21 system-196-link -> /nix/store/6nl03iw4kb38jqd1w51i4cjg1wxj8yrf-nixos-system-spinoza-23.05.20230502.1a411f2
```

How do I clean up old system generations?

**Comment by lovesegfault** [comment]
I did `sudo nix profile wipe-history --profile /nix/var/nix/profiles/system`, which helped, but the entries are all still in `/boot`:

```
$ ls -l /boot/loader/entries
total 60
-rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-181.conf
-rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-182.conf
-rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-183.conf
-rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-184.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-185.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-186.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-187.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-188.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-189.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-190.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-191.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-192.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-193.conf
-rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-194.conf
-rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-195.conf
```

**Comment by RaitoBezarius** [comment]
I don't think lanzaboote does a special thing here, @nikstur any idea?
(we don't add gc roots to all systems, do we?!)

**Comment by RaitoBezarius** [comment]
> I did `sudo nix profile wipe-history --profile /nix/var/nix/profiles/system`, which helped, but the entries are all still in `/boot`:
> 
> ```
> $ ls -l /boot/loader/entries
> total 60
> -rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-181.conf
> -rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-182.conf
> -rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-183.conf
> -rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-184.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-185.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-186.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-187.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-188.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-189.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-190.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-191.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-192.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-193.conf
> -rwxr-xr-x 1 root root 813 May  4 07:11 nixos-generation-194.conf
> -rwxr-xr-x 1 root root 806 May  4 07:11 nixos-generation-195.conf
> ```

Actually, I'm not sure we will cleanup this for you.

Basically, when it comes to "broken generation" or "stuff we do not understand", we do not delete them.
This is a compromise between `rm -rf /boot/EFI` (which we did once) and doing nothing (which we did at a time too).

**Comment by nikstur** [comment]
Afaik, the Nix GC does not touch anything on the ESP. If you want to get rid of old entries, you need to GC old generations (i.e. the ones in `/nix/var/nix/profiles`) and set a configuration limit via `boot.lanzaboote.configurationLimit`. The only way Lanzaboote (and systemd-boot on NixOS afaik) delete generations from the ESP is when you have set a `configurationLimit`.

I don't know why `nix-collect-garbage -d` didn't delete anything in `/nix/var/nix/profiles` but I just ran it on a non-Lanzaboote machine and it also does not delete anything in `/nix/var/nix/profiles`. I don't think it has anything to do with Lanzaboote.

**Comment by RaitoBezarius** [comment]
I believe this is https://github.com/NixOS/nix/issues/8294.

**Comment by RaitoBezarius** [comment]
I will close this, don't hesitate to open if you think this is a Lanzaboote problem.
