### ISSUE TITLE
nix-collect-garbage -d removes all generations from boot menu?

### ISSUE THREAD

**Issue by vroad** [nix-community/lanzaboote#190]
I ignored following errors when switching NixOS configuration because lanzaboote often boots fine even after showing backtrace like this.

```
❯ nix run .#nixos-rebuild -- switch --flake .#b660m --target-host root@b660m
warning: Git tree '/home/nixos/git/nixos-configuration-b660m' is dirty
warning: Git tree '/home/nixos/git/nixos-configuration-b660m' is dirty
building the system configuration...
warning: Git tree '/home/nixos/git/nixos-configuration-b660m' is dirty
copying 0 paths...
Malformed generation: Failed to build generation from link: GenerationLink { version: 36, path: "/nix/var/nix/profiles/system-36-link" }

Caused by:
    0: Failed to parse bootspec json
    1: unknown variant `org.nixos.bootspec.v1`, expected `v1` at line 2 column 25

Stack backtrace:
   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
   1: lanzatool::generation::Generation::from_link
   2: lanzatool::install::Installer::install
   3: lanzatool::cli::Cli::call
   4: lanzatool::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal
   8: main
   9: __libc_start_call_main
  10: __libc_start_main_alias_1
  11: _start
activating the configuration...
setting up /etc...
reloading user units for root...
setting up tmpfiles
```

I tested that my machine boots after switchng to new generation, then ran `sudo nix-collect-garbage -d`. However this removed all generations from boot menu. Only option left on the boot menu is `Reboot into Firmware Interface`.

**Comment by RaitoBezarius** [comment]
What version of lanzaboote are you running? It seems like you are running a Bootspec v1 with a pre-Bootspec v1 lanzaboote.

**Comment by vroad** [comment]
Thank you for the answer.

> What version of lanzaboote are you running? It seems like you are running a Bootspec v1 with a pre-Bootspec v1 lanzaboote.

I should have checked that... I just forgot to change my flake input for lanzaboote (I pinned lanzaboote version because I had issues in the past).
Everything worked as expected after updating lanzaboote.
