### ISSUE TITLE
Potentially wrong package platforms for lanzaboote_stub

### ISSUE THREAD

**Issue by therealr5** [nix-community/lanzaboote#205]
Hey there, I noticed that my system updates took way longer than usual and wanted to dig a bit.
Aparrently my system needed to fully compile the `rustc-x84_64-windows` compiler to build the lanzaboote stub as it is only defined for windows platforms in here:

https://github.com/nix-community/lanzaboote/blob/c758cdad465e0c8174db57dc493f51a89f0e3372/nix/packages/stub.nix#L27

Is this intended? Please correct me if I'm wrong but it seems kinda weird to me since lanzaboote implements secureboot solely for linux platforms.

**Comment by nikstur** [comment]
It's Windows because the UEFI environment (where the stub runs) is for all intents and purposes the same as Windows. That's why the tool is built on your hostPlatform while the stub is cross compiled to the windows targets you have listed.

**Comment by RaitoBezarius** [comment]
> Hey there, I noticed that my system updates took way longer than usual and wanted to dig a bit. Aparrently my system needed to fully compile the `rustc-x84_64-windows` compiler to build the lanzaboote stub as it is only defined for windows platforms in here:
> 
> https://github.com/nix-community/lanzaboote/blob/c758cdad465e0c8174db57dc493f51a89f0e3372/nix/packages/stub.nix#L27
> 
> Is this intended? Please correct me if I'm wrong but it seems kinda weird to me since lanzaboote implements secureboot solely for linux platforms.

You should avoid tracking the branch master as this is the cutting edge state of this branch, and rather use the most recent tag (0.3.0), if you want to avoid building long toolchains.
