### ISSUE TITLE
Sometimes the boot entry title is missing generation + build time

### ISSUE THREAD

**Issue by colemickens** [nix-community/lanzaboote#220]
I'm not sure what's up here, but I've been building and deploying generations to this machine over the past few days.

But, look at generation 247, the title is different:
* `title: NixOS Tapir 23.11.20230903.9695c13 (Linux 6.4.14) (Generation 248, Built on 2023-09-06)`
* `title: NixOS Tapir 23.11.20230905.2f4e16a (Linux 6.4.14) `
* `title: NixOS Tapir 23.11.20230903.9695c13 (Linux 6.4.14) (Generation 246, Built on 2023-09-05)`

Full(er) `bootctl list` output:

```
...
...

         type: Boot Loader Specification Type #2 (.efi)
        title: NixOS Tapir 23.11.20230903.9695c13 (Linux 6.4.14) (Generation 248, Built on 2023-09-06)
           id: nixos-generation-248.efi
       source: /efi//EFI/Linux/nixos-generation-248.efi
     sort-key: lanza
      version: Generation 248, Built on 2023-09-06
        linux: /efi//EFI/Linux/nixos-generation-248.efi
      options: init=/nix/store/12208j9s629ar1gwp7nqvx3vzrbamwhz-nixos-system-zeph-23.11.20230903.9695c13/init mitigations=off amd_pstate=active pcie_aspm.policy=powersupersave nohibernate loglevel=4

         type: Boot Loader Specification Type #2 (.efi)
        title: NixOS Tapir 23.11.20230905.2f4e16a (Linux 6.4.14)
           id: nixos-generation-247.efi
       source: /efi//EFI/Linux/nixos-generation-247.efi
     sort-key: lanza
      version: Generation 247, Built on 2023-09-05
        linux: /efi//EFI/Linux/nixos-generation-247.efi
      options: init=/nix/store/infyiwivv58bfjnigqns2idnl6rb9663-nixos-system-zeph-23.11.20230905.2f4e16a/init mitigations=off amd_pstate=active nohibernate loglevel=4

         type: Boot Loader Specification Type #2 (.efi)
        title: NixOS Tapir 23.11.20230903.9695c13 (Linux 6.4.14) (Generation 246, Built on 2023-09-05)
           id: nixos-generation-246.efi
       source: /efi//EFI/Linux/nixos-generation-246.efi
     sort-key: lanza
      version: Generation 246, Built on 2023-09-05
        linux: /efi//EFI/Linux/nixos-generation-246.efi
      options: init=/nix/store/8a07nkj1fjc61grnapfjjzmmzmghzg91-nixos-system-zeph-23.11.20230903.9695c13/init mitigations=off amd_pstate=active nohibernate loglevel=4

         type: Automatic
        title: Windows Boot Manager
           id: auto-windows
       source: /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f

```

I noticed this, as it's visible on the boot menu: 
![PXL_20230906_132457264](https://github.com/nix-community/lanzaboote/assets/327028/6a1306a1-e305-47b4-9469-98343f48e01e)

**Comment by RaitoBezarius** [comment]
I do notice the same behavior.

**Comment by colemickens** [comment]
I will say, reviewing the image I posted, it's a bit odd that my nixpkgs git rev seems to ... change/advance and then revert back. I'm super jet-lagged so I'm afraid to speculate further right now.

**Comment by nikstur** [comment]
Can you objdump the UKI in question (or better only the .osrel section)? I don't see a code path that can silently fail when generating the os-release (which determines how a generation is displayed). If the tool can't read the build time, for example it would display: "Generation X, Built on Unknown"

**Comment by blitz** [comment]
Same here:

![image](https://github.com/nix-community/lanzaboote/assets/37907/1a050f18-fde1-43ab-b057-2ea3086a30fc)

Wow. My display is dirty. ;)

Let me extract some osrel sections...

**Comment by blitz** [comment]
Broken:
```shell
/boot/EFI/Linux🔒 
❯ objdump -s -j .osrel nixos-generation-445.efi

nixos-generation-445.efi:     file format pei-x86-64

Contents of section .osrel:
 1400203cc 49443d6c 616e7a61 0a505245 5454595f  ID=lanza.PRETTY_
 1400203dc 4e414d45 3d4e6978 4f532053 746f6174  NAME=NixOS Stoat
 1400203ec 2032332e 30352e32 30323330 3930352e   23.05.20230905.
 1400203fc 34303737 61306520 284c696e 75782036  4077a0e (Linux 6
 14002040c 2e352e31 290a5645 5253494f 4e5f4944  .5.1).VERSION_ID
 14002041c 3d47656e 65726174 696f6e20 3434352c  =Generation 445,
 14002042c 20427569 6c74206f 6e203230 32332d30   Built on 2023-0
 14002043c 392d3037 0a                          9-07.           
```

Good:
```shell
/boot/EFI/Linux🔒 
❯ objdump -s -j .osrel nixos-generation-443.efi

nixos-generation-443.efi:     file format pei-x86-64

Contents of section .osrel:
 1400203cc 49443d6c 616e7a61 0a505245 5454595f  ID=lanza.PRETTY_
 1400203dc 4e414d45 3d4e6978 4f532053 746f6174  NAME=NixOS Stoat
 1400203ec 2032332e 30352e32 30323330 3832322e   23.05.20230822.
 1400203fc 61313666 37656220 284c696e 75782036  a16f7eb (Linux 6
 14002040c 2e342e31 31290a56 45525349 4f4e5f49  .4.11).VERSION_I
 14002041c 443d4765 6e657261 74696f6e 20343433  D=Generation 443
 14002042c 2c204275 696c7420 6f6e2032 3032332d  , Built on 2023-
 14002043c 30382d32 370a                        08-27.  
```

**Comment by blitz** [comment]
It seems systemd-boot only shows `VERSION_ID` when `PRETTY_NAME` is not unique. At least that would be my guess when looking at my and @colemickens screenshots.

So should we just add the generation number to `PRETTY_NAME` if people want to know it?

**Comment by colemickens** [comment]
Alternatively, maybe a feature request to `systemd-boot` to always display `VERSION_ID`, or an option to do so?

**Comment by blitz** [comment]
It's probably easier to include the generation number in the pretty name.

**Comment by nikstur** [comment]
> It seems systemd-boot only shows `VERSION_ID` when `PRETTY_NAME` is not unique.

Thats pretty surprising behaviour. We should open a systemd issue, but I agree that we should fix it quickly by including the generation number in pretty name.
