### ISSUE TITLE
Secure Boot Broken with edk2 202308

### ISSUE THREAD

**Issue by blitz** [nix-community/lanzaboote#240]
#216 discovered that EDK2 202308 breaks our tests. Unfortunately, this is the default in Nixpkgs now. @RaitoBezarius has bisected this to the change in EDK2 that updates OpenSSL to version 3.

**Comment by secufoe** [comment]
Has this problem been mentioned upstream? I can't find a related issue. What's the plan to resolve this?

**Comment by RaitoBezarius** [comment]
I need to test but I believe OpenSSL 3 is too big and the build system of 202308 does not assert if the objects fit in the final binary.

**Comment by secufoe** [comment]
okay, i don't really understand why the binary wouldn't just be bigger. btw isn't nixpkgs' EDK2 on 202311 (same problem)?

**Comment by secufoe** [comment]
Do you have the resulting commit from your bisect? Or the test that you used for the bisect (quickest you can find :wink:)

**Comment by RaitoBezarius** [comment]
OpenSSL3 bump is the introducing commit.

**Comment by nikstur** [comment]
Nixpkgs has `OVMFFull` which has Secure Boot enabled but on a very brief look it didn't work either.

**Comment by RaitoBezarius** [comment]
I have a local tree where I am able to make almost all tests pass, but certain still fail, I will open it.

**Comment by nikstur** [comment]
Closed by #318
