### ISSUE TITLE
uefi stub contains timestamp of compilation

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/lanzaboote#260]
The uefi stub contains a timestamp of the compilation even when done in the nix sandbox which is not great for reproducibility. 

```
 ➜ objdump -p target/x86_64-unknown-uefi/debug/lanzaboote_stub.efi | head -10

target/x86_64-unknown-uefi/debug/lanzaboote_stub.efi:     file format pei-x86-64

Characteristics 0x22
        executable
        large address aware

Time/Date               Mon Nov 13 20:02:35 2023
Magic                   020b    (PE32+)
MajorLinkerVersion      14
```

I tried to pass ``--no-insert-timestamp`` to lld but that didn't work or I didn't pass it correctly.

**Comment by blitz** [comment]
Thanks for raising this. Can you check whether #261 solves this for you?
