### ISSUE TITLE
Nix flake check is broken

### ISSUE THREAD

**Issue by blitz** [nix-community/lanzaboote#264]
It looks like #257 broke `nix flake check`:

```
❯ nix -L flake check 
error: 'unsupportedChecks' is not a valid system type, at «none»:0
(use '--show-trace' to show detailed location information)
```

This is unfortunate, because this is my "manual CI". @RaitoBezarius, is there a way to fix this?

Happens with Nix 2.13.6.

**Comment by RaitoBezarius** [comment]
Will fix yes.
