### ISSUE TITLE
Secureboot with Encrypted ZFS?

### ISSUE THREAD

**Issue by zyansheep** [nix-community/lanzaboote#277]
Hi, awesome project!

I'm playing around with lanzaboote on my system and after adding the flake input and configuration, I get this message:
```
Definition values:
       - In `/nix/store/4jglns5wqzzwcjy9pqkf5k8fx74h8c7h-source/nixos/modules/system/boot/loader/grub/grub.nix': <derivation install-grub.sh>
       - In `/nix/store/4jglns5wqzzwcjy9pqkf5k8fx74h8c7h-source/nixos/modules/system/boot/loader/external/external.nix': <derivation bootinstall>
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```
I believe this is because I have this piece of configuration:
```
boot.loader.grub = {
    zfsSupport = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    mirroredBoots = [ { devices = ["nodev"]; path = "/boot"; } ];
  };
```
Which is required due to zfs. Does lanzaboote's bootloader support zfs?

**Comment by nikstur** [comment]
Thank you!

We use systemd-boot, which does NOT support boot partition encryption. We might support multiple bootloader backends in the future but we currently do not have concrete plans for this.

**Comment by zyansheep** [comment]
Wait, I'm confused, is the grub config I pasted above "boot partition encryption"? I thought it was just configuring the bootloader to decrypt the zfs pool before continuing startup.

Does this mean there is no way to have secureboot *and* an encrypted root?
