### ISSUE TITLE
bootctl does not like our stubs any more

### ISSUE THREAD

**Issue by alois31** [nix-community/lanzaboote#296]
Since systemd version 255, `bootctl` does not like our stubs any more and prints warning messages like the following:

    Parsed PE file '/boot/EFI/Linux/nixos-generation-1000-gcd7loldrxsnbg7jhr5f7s7erksoixpj6btz4nebkhivlzprqn3q.efi' is not a UKI.

They still show in the systemd-boot menu and boot properly.

**Comment by repomaa** [comment]
Could be related: #295

**Comment by alois31** [comment]
> We could rename `.initrdp` to `.initrd` and `.kernelp` to `.linux` to fix this.

I guess that could work, until systemd starts to peek into the contents of these sections only to find (or even worse, not find) things it doesn't like…

**Comment by blitz** [comment]
> > We could rename `.initrdp` to `.initrd` and `.kernelp` to `.linux` to fix this.
> 
> I guess that could work, until systemd starts to peek into the contents of these sections only to find (or even worse, not find) things it doesn't like…

True, but the only solution that would avoid this is to get thin stub support into the upstream UKI stub.

**Comment by RaitoBezarius** [comment]
Even if we did (with the PRs for addons I have been cooking, stuck mostly on dealing with the ukify Python script…), we would not get the hashing scheme we have and we would be forced to sign all addons using Secure Boot, a bit sad.
