### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/lanzaboote#30]
Depends on ~https://github.com/msekletar/sbsigntool/issues/2~ ~https://github.com/NixOS/nixpkgs/pull/207171~ #31

**Comment by leg7** [comment]
Does the project support aarch64 at all? I would like to try it on my raspberry pi but I'm worried of bricking it with the OTP memory that holds the key hashes.

**Comment by nikstur** [comment]
We intend to support AARCH64. However we will only support UEFI systems (which afaik the rpi does not use).

**Comment by RaitoBezarius** [comment]
> Does the project support aarch64 at all? I would like to try it on my raspberry pi but I'm worried of bricking it with the OTP memory that holds the key hashes.

We depend on a systemd new release to support AArch64 for now.

**Comment by RaitoBezarius** [comment]
> We intend to support AARCH64. However we will only support UEFI systems (which afaik the rpi does not use).

RPi 3|4 supports UEFI: https://github.com/pftf/RPi4

**Comment by leg7** [comment]
> > Does the project support aarch64 at all? I would like to try it on my raspberry pi but I'm worried of bricking it with the OTP memory that holds the key hashes.
> 
> We depend on a systemd new release to support AArch64 for now.

Is it because of an issue with systemd?

**Comment by RaitoBezarius** [comment]
> > > Does the project support aarch64 at all? I would like to try it on my raspberry pi but I'm worried of bricking it with the OTP memory that holds the key hashes.
> > 
> > 
> > We depend on a systemd new release to support AArch64 for now.
> 
> Is it because of an issue with systemd?

Yes, see https://github.com/systemd/systemd/issues/27821

**Comment by leg7** [comment]
Isn't it fixed though?

**Comment by RaitoBezarius** [comment]
> Isn't it fixed though?

Yes, but is it released? :)

> We depend on a systemd **new release** to support AArch64 for now.

**Comment by leg7** [comment]
Oh yeah, my bad sorry

**Comment by alex-startengine** [comment]
systemd-boot still broken on my aarch64 efi system. using systemd 253.5

**Comment by nikstur** [comment]
This should be fixed in systemd 254 (so the next release). They significantly refactored all their uefi code and specifically got rid of gnu-efi which caused a lot of problems.

**Comment by alex-startengine** [comment]
thanks for the info @nikstur !
