### ISSUE TITLE
Using Lanzaboote without Flakes or Niv

### ISSUE THREAD

**Issue by scolby33** [nix-community/lanzaboote#315]
Is it possible to use this project without Flakes or Niv?

I've tried like
```nix
let
  lanzaboote = builtins.fetchTarball "https://github.com/nix-community/lanzaboote/archive/refs/tags/v0.3.0.tar.gz"
in
{
  imports = [ "${lanzaboote}/nix/modules/lanzaboote.nix" ];

  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/etc/secureboot";
  };
}
```

This results in `error: attribute 'lzbt' missing` at `lanzaboote.nix:57`.

I read the the `sources.nix` generated by a test `niv` invocation, but I can't figure out what processes it does to actually build the `lzbt` package as defined in the Flake and make it available to the non-Flake world.

**Comment by RaitoBezarius** [comment]
Yes, it's possible, but I don't think you injected the overlay, therefore `pkgs.lzbt` is unavailable.

**Comment by bjornfor** [comment]
Where in flake.nix is that overlay defined? Is it the easyOverlay in https://github.com/nix-community/lanzaboote/blob/73fec69386e8005911e15f3abe6bb6cee7fd9711/flake.nix#L41-L44 that adds `pkgs.lzbt`?

**Comment by scolby33** [comment]
Could you expand on what you mean by injecting the overlay? What would a `configuration.nix` snippet for that look like?

**Comment by justinas** [comment]
Here's the entirety of my flakeless set-up:

```nix
{ lib, pkgs, ... }:
let
  lanzaboote = import (import ../../lanzaboote.nix);
in
{
  imports = [ lanzaboote.nixosModules.lanzaboote ];
  nixpkgs.overlays = [ lanzaboote.overlays.default ];

  boot.loader.grub.enable = false;
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/etc/secureboot";
  };

  environment.systemPackages = with pkgs; [ sbctl ];
}
```

Where `lanzaboote.nix` is:

```nix
builtins.fetchGit {
  name = "lanzaboote";
  url = "https://github.com/nix-community/lanzaboote";
  ref = "refs/tags/v0.3.0";
  rev = "64b903ca87d18cef2752c19c098af275c6e51d63";
}
```

**Comment by scolby33** [comment]
Thanks @justinas, that worked perfectly! I slightly simplified by doing this in my `configuration.nix`:
```
{ config, pkgs, lib, ... }:
let
  lanzaboote = import (builtins.fetchGit { ... });
in
{
  imports = [ lanzaboote.nixosModules.lanzaboote ];
  nixpkgs.overlays = [ lanzaboote.overlays.default ];
  ...
}
```
