### ISSUE TITLE
Nvidia support?

### ISSUE THREAD

**Issue by resignationinfinite** [nix-community/lanzaboote#319]
Most distros need to enroll a MOK to support Nvidia proprietary drivers with Secure Boot enabled, is this the case for Nix and if so does lanzaboote support this? Couldn't find anything in the wiki...

**Comment by RaitoBezarius** [comment]
No, you don't need a MOK to support nVidia proprietary drivers. Lanzaboote is "bring your own keys" Secure Boot for now, there's no shim involved.

I run Secure Boot with nVidia proprietary drivers without any action from my end.

**Comment by blitz** [comment]
Please re-open if this didn't answer your question!

**Comment by Saiv46** [comment]
How do I make sure that Secure Boot won't brick my system? It already happened with me before - Nvidia proprietary firmware is signed with Microsoft keys, and they won't pass signature checks before motherboard could even POST. Then the only option is to either either yank out that graphics card or reset CMOS.

Oh, and even when keeping Microsoft keys during enrolling with `sbctl`, it still leads to exact problem of motherboard refusing to boot.

**Comment by mrphil2105** [comment]
@Saiv46 What graphics card do you have? I have an Asus RTX 5070 Ti TUF OC, and I am thinking of using lanzaboote, but I am unsure whether I will run into the same problem you are experiencing, even if I enroll the Microsoft keys as well.

**Comment by Saiv46** [comment]
@mrphil2105 I use RTX 3050 LP, recently I had to reset my secure boot keys completely and start from the scratch. At least now it works for me.

You should propably write somewhere the sequence on how to get to BIOS, navigate to secure boot options, turn it off, then save and reboot (you'll do that blind!). And if you use TPM, make sure to have a passphrase as a backup everywhere.
