### ISSUE TITLE
Backup keys and other stuff

### ISSUE THREAD

**Issue by arthsmn** [nix-community/lanzaboote#333]
Hey! I would like to know which files do I need to backup in /etc/secureboot to have a functional secureboot if I reinstall the OS. I also would like to know if I can just use sops-nix to handle those files. Thanks!

**Comment by RaitoBezarius** [comment]
You need to backup all of `/etc/secureboot`, you can use `sops-nix` to handle those files, certainly!

**Comment by RaitoBezarius** [comment]
FWIW, you only need the `key` directory at any time on the system, you don't need the `PK`, `KEK` after the initial provisioning.

**Comment by arthsmn** [comment]
Thanks!
