### ISSUE TITLE
Change bootloader font size?

### ISSUE THREAD

**Issue by 8bitbuddhist** [nix-community/lanzaboote#340]
Is there any way to increase the size of the font used during pre-boot (the generation selection screen)? I'm aware of [boot.loader.systemd-boot.consoleMode](https://search.nixos.org/options?channel=unstable&show=boot.loader.systemd-boot.consoleMode&from=0&size=50&sort=relevance&type=packages&query=systemd-boot), but is there a similar option for Lanzaboote?

**Comment by MaxHearnden** [comment]
Try setting `boot.lanzaboote.settings.consoleMode`
