### ISSUE TITLE
Pin lanzaboote at specific commit?

### ISSUE THREAD

**Issue by natterangell** [nix-community/lanzaboote#350]
Hi,

I experience the same boot delay as mentioned in issue [341](https://github.com/nix-community/lanzaboote/issues/341) on the 0.3.0. release. I issued `niv update lanzaboote -b master` to track master instead, and the issue went away as the fix was merged in commit [850f273](https://github.com/nix-community/lanzaboote/commit/850f27322239f8cfa56b122cc9a278ab99a49015).

I'm not very experienced with niv and git, so I just wonder if there is a way I can use niv to track the current master tree at a given commit, so that I don't have to wait for lanzaboote to rebuild from scratch every time there's been a new commit? Then I can switch to 0.4.0 release when that is ready, as everything else works great!

**Comment by nikstur** [comment]
You can either just track master, pin to a specific commit with `niv update -r <commit hash>`, or track the newest [v0.4.0 release](https://github.com/nix-community/lanzaboote/releases/tag/v0.4.0).
