### ISSUE TITLE
Parsed PE file is not a UKI warning message

### ISSUE THREAD

**Issue by cig0** [nix-community/lanzaboote#354]
Hi,

Thanks for putting this project together.

I am getting these warning messages:

```console
$ bootctl status
Parsed PE file '/boot/EFI/Linux/nixos-generation-140.efi' is not a UKI.
Parsed PE file '/boot/EFI/Linux/nixos-generation-141.efi' is not a UKI.
```

From what I gathered online—and if I understand it correctly—it indicates that the EFI files are not recognized as a Unified Kernel Image (UKI).

Other than the warning messages, I believe everything else is working correctly:

```console
System:
      Firmware: UEFI 2.70 (American Megatrends 5.19)
 Firmware Arch: x64
   Secure Boot: enabled (user)
  TPM2 Support: yes
  Measured UKI: no
  Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 255.6
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Enroll SecureBoot keys
               ✓ Retain SHIM protocols
               ✓ Menu can be disabled
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/aa4ba82a-6eeb-41fa-8e08-0307fa5074ec
         File: └─/EFI/SYSTEMD/SYSTEMD-BOOTX64.EFI

Random Seed:
 System Token: set
       Exists: yes
```

I checked several times the installation guide, and I'm pretty sure I didn't miss any step.
My host information is a follows:

```console
$ nix-info --host-os -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.05 (Uakari), 24.05.20240606.9b5328b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/home/cig0/.nix-defexpr/channels/nixpkgs`
```

Thanks

**Comment by RaitoBezarius** [comment]
We can lie and make it appear as if it was a UKI, but unfortunately this is not true, lanzaboote binaries are not UKI, they are partial kernel images. Thus, there's not a lot that can be done, except a game of faking it as a UKI.

A good solution would be to rework things to have it more aligned with systemd upstream terminology and vision.

**Comment by cig0** [comment]
Ah perfect! Thanks for letting me know! Would you like me to add a little addendum to the setup guide, to avoid this noise in the future?
