### ISSUE TITLE
error: Stable 1.78.0 is not available | v0.4.0

### ISSUE THREAD

**Issue by PassiveLemon** [nix-community/lanzaboote#357]
[lanzlog.log](https://github.com/user-attachments/files/15754261/lanzlog.log)

**Comment by matthewpi** [comment]
After editing your `flake.nix` to update from 0.3.0 to 0.4.0 you will need to run `nix flake update` to update `crane` and `rust-overlay`.  I just ran into this issue myself.

**Comment by PassiveLemon** [comment]
Can confirm, running a flake update is the solution.
