### ISSUE TITLE
Kernel hash does not match!

### ISSUE THREAD

**Issue by dasehak** [nix-community/lanzaboote#376]
When I try to boot the following message prints:
```
[ERROR]: stub/src/thin.rs@070: Kernel hash does not match!
Failed to execute Generation Name (\path\to\generation): Security violation
```
Reinstalling the kernel does not help

**Comment by blitz** [comment]
Hi @dasehak! Did you have a working setup before? Did anything change? Can you elaborate a bit on your setup (hardware, NixOS version/configuration, Lanzaboote version, ...).

**Comment by dasehak** [comment]
> Hi @dasehak! Did you have a working setup before? Did anything change? Can you elaborate a bit on your setup (hardware, NixOS version/configuration, Lanzaboote version, ...).

1. No
2. No 
3.1. X99-based motherboard, Intel Xeon E5-2678 v3
3.2. NixOS 24.11.20240715.f193f94 (Vicuna) x86_64, config: https://github.com/dasehak/nixos-config-remake
3.3. 0.4.1
