### ISSUE TITLE
No space left on device despite doing literally everything to fix it

### ISSUE THREAD

**Issue by deviantsemicolon** [nix-community/lanzaboote#377]
I've done everything recommended in troubleshooting to fix this. I have a 1GB EFI partition, no generations on my system, and i've deleted as many kernels as i can without making the system become unbootable. None of it worked. 

Error output is as follows:

`Failed to install generation.: Failed to install the initrd.: Failed to copy from "/tmp/.tmpkdwknv/iwDDIJt0JV3bCEV7t1SzOC9qZj0UwxRX" to the temporary file "/boot/EFI/nixos/initrd-6.9.8-dmwfy74km2vqh7qv6ddhv3kgbaeh2fqqlv63cofigdshaubfp77q..tmp": No space left on device (os error 28)`

**Comment by qm3ster** [comment]
Why is this closed? 👀

**Comment by anpin** [comment]
hitting this too, clearing generations doesn't seem to help. were you able to fix this?

**Comment by anpin** [comment]
ok got it. as mentioned in [troubleshooting](https://github.com/nix-community/lanzaboote/blob/master/docs/TROUBLESHOOTING.md) one has remove kernels manuallly
