### ISSUE TITLE
Lanzatool skips already existing files even if they are not signed

### ISSUE THREAD

**Issue by RaitoBezarius** [nix-community/lanzaboote#39]
If you remove a sig of a systemd-bootx64.efi, lanzatool will turn a blind eye and not sign it.

Causing surprising behaviors such as security violation :-((((

**Comment by nikstur** [comment]
sd-boot is not signed if it already existed

**Comment by RaitoBezarius** [comment]
same for kernels or any file actually I think

**Comment by nikstur** [comment]
Yes, but for sd-boot it matters even on an "ignore" policy where we ignore old kernels and initrds

**Comment by blitz** [comment]
Related to #56 and #55.

**Comment by vroad** [comment]
Can't we just verify signature of existing files and sign them too, instead of just signing only non-existing files?

**Comment by RaitoBezarius** [comment]
> Can't we just verify signature of existing files and sign them too, instead of just signing only non-existing files?

Yes this is what is planned.

**Comment by nikstur** [comment]
#76 solved our issue with newer/malformed/unsiged systemd-boot binaries. It did not solve the issue with existing unsiged kernels.

**Comment by nikstur** [comment]
#75 & Implementing a solution for #68 will fix this issue.

**Comment by mweinelt** [comment]
Hit this and one more `nix-collect-garbage -d` and another `rebuild` solved this for me.

**Comment by nikstur** [comment]
Now that #75 is merged, the only issue left here is that the stub/UKI might not be signed and will not be resigned or overwritten. This, however, could only happen if the user manually removed the signature from one of them.
