### ISSUE TITLE
Ignore Hash Mismatches with Secure Boot Disabled

### ISSUE THREAD

**Issue by blitz** [nix-community/lanzaboote#58]
When lanzaboote doesn't find kernels/initrds that match its hashes, it will decline to boot them regardless of the Secure Boot setup. In combination with #56 and manually signing of initrds/kernels this can easily result in an unbootable system.

Lanzaboot should ignore hashes when Secure Boot is not enabled to give users a good recovery path that doesn't involve booting into a recovery system.

**Comment by RaitoBezarius** [comment]
Implementation idea: try to LoadImage a dummy and catch the security violation?

**Comment by blitz** [comment]
I think this can be very elegantly implemented by using LoadImage on the Linux kernel. We will not sign it after the PE loading PR goes through. So we can use it to detect Secure Boot.
