### ISSUE TITLE
Boot menu not showing up even when multiple generations are available

### ISSUE THREAD

**Issue by vroad** [nix-community/lanzaboote#67]
I'm not sure on which version it stopped working since I run lanzaboote-installed machine headlessly most of the time. What could be the cause of the issue?
The system boots fine, I can't just select previous generations.

**Comment by RaitoBezarius** [comment]
Which revision are you running at the moment?

**Comment by vroad** [comment]
@RaitoBezarius 
https://github.com/NixOS/nixpkgs/commit/6c8644fc37b6e141cbfa6c7dc8d98846c4ff0c2e
https://github.com/nix-community/lanzaboote/commit/367d36775d8058ef7f2e171f9397dbff89cd22dc

**Comment by nikstur** [comment]
A few questions: 

1. Do you see the screen where you can usually choose a generation, and there is just nothing to choose from? Or does that screen never even show?
2. Do you have a loader.conf that sets a timeout?

On the top of my head, the only thing I can think of is that there is something fishy going on with the new `sort-key` (lanza instead of nixos) introduced in  #50

**Comment by vroad** [comment]
> 1. Do you see the screen where you can usually choose a generation, and there is just nothing to choose from? Or does that screen never even show?

The screen never even show.

> 2\. Do you have a loader.conf that sets a timeout?

In `/boot/loader`? I don't have loader.conf in that directory. Another machine has one in `/boot/loader`.
I probably have removed that file by myself. Should I re-create the file manually? I expected nixos-rebuild command to create loader.conf automatically.

**Comment by vroad** [comment]
I re-created by building previous version of NixOS configuration, and boot menu started working again.
But shouldn't `nixos-rebuild` create the file automatically if it's missing when the configuration is built?

**Comment by nikstur** [comment]
Yes it should ^^. It just doesn't yet. We're tracking it here: https://github.com/nix-community/lanzaboote/issues/9#issuecomment-1370351049 

So the solution was that a loader.conf with an appropriate timeout was missing, right? This can be closed then.
