### ISSUE TITLE
Isn't it insecure to store the key for signing bootloaders and kernels in unencrypted drive?

### ISSUE THREAD

**Issue by vroad** [nix-community/lanzaboote#70]
Docs doesn't mention anything about storing keys in an encrypted drive.

I believe that secure boot should always be used with full disk encryption, without that an attacker could read signing keys stored in the device, or store malicious programs to the system partition.

To protect the key and the certificate from such attack, users should either

1. Password-protect system drive with LUKS
2. Password-protect system drive with LUKS and run systemd-cryptenroll with `--tpm2-pcrs=0+2+4+7` if you want to auto-unlock the drive (though you need to re-enter password everytime bootloader is updated, as I described in https://github.com/nix-community/lanzaboote/issues/61#issuecomment-1385044361)

It might not be relevant if the drive is not removable and booting from other devices is not allowed, but most of the time that's not the case.

**Comment by RaitoBezarius** [comment]
Another way to see it is that once we have PKCS#11 engine support, it is possible to sign your boot files using a smartcard or similar devices which do not leak the private key material, achieving what is wanted here.

**Comment by blitz** [comment]
This sounds like we at least need some guidelines for users, who to not completely undermine their secure boot setup. Enabling full disk encryption is definitely one point.

**Comment by RaitoBezarius** [comment]
Semi-addressed by #89.

**Comment by blitz** [comment]
I would also say wih #89, we have at least an initial warning in place.
