### ISSUE TITLE
Parsing os-release has incorrect quotes handling

### ISSUE THREAD

**Issue by blitz** [nix-community/lanzaboote#77]
[os-release](https://www.freedesktop.org/software/systemd/man/os-release.html) has more syntax complexity than what we currently handle. Particularly entries with quotes in them will be handled the wrong way.

**Comment by blitz** [comment]
I think it is better now, but still not quite there. We should check what systemd-stub does for reference. My issues are that we accept things that are forbidden by the "spec":

`Shell special characters ("$", quotes, backslash, backtick) must be escaped with backslashes, following shell style.`

**Comment by dasJ** [comment]
I actually think a lenient parser is more appreciated by the user while not introducing any (security) issues

**Comment by blitz** [comment]
We should try to emulate what systemd-stub does. In any case, we should document where we deviate from the "specification".

**Comment by AkechiShiro** [comment]
@blitz I'd like to help in this issue, a first step would be to take a look at `systemd-stub`'s source code for parsing `os-release` ? And start writing WIP documentation ?

> I think it is better now, but still not quite there. We should check what systemd-stub does for reference. My issues are that we accept things that are forbidden by the "spec":

By "spec", which spec are you referencing here ? Bootspec ?

**Comment by RaitoBezarius** [comment]
> @blitz I'd like to help in this issue, a first step would be to take a look at `systemd-stub`'s source code for parsing `os-release` ? And start writing WIP documentation ?

I would argue that it would be better to implement the format properly while referring to the upstream documentation.
Redoing documentation will just get us documentation that will bitrot.

> > I think it is better now, but still not quite there. We should check what systemd-stub does for reference. My issues are that we accept things that are forbidden by the "spec":
> 
> By "spec", which spec are you referencing here ? Bootspec ?

The specification for os-release scheme.

**Comment by RaitoBezarius** [comment]
I spoke a bit with systemd upstream, the true "spec" is the code and until there's some stuff to automate sync between "spec" (manpage) and code (true spec), there should be no expectation we have specification.

In practice, the spirit of os-release is subset of Bourne shell without interpolation or variable assignment. As long as we are not too far from this, I would not prioritize this.

**Comment by AkechiShiro** [comment]
Thanks for the update, is there any issue tracking an effort of having a better spec (i.e. issue tracking work on code spec that is somewhat equivalent to manpage spec in upstream systemd) to this day, so that, we could know when we could start prioritizing this work ?
