### ISSUE TITLE
Atomic writes to ESP

### ISSUE THREAD

**Issue by nikstur** [nix-community/lanzaboote#80]
All writes to the ESP should be atomic. This means specifically that files should first be written to the esp with a `.tmp` suffix and then moved to the actual file name (which is an atomic operation on POSIX).

**Comment by RaitoBezarius** [comment]
FWIW relevant discussion for ESPs: https://yhbt.net/lore/all/20191023115001.vp4woh56k33b6hiq@pali/t/
