### ISSUE TITLE
Support flicker-free boot

### ISSUE THREAD

**Issue by dasJ** [nix-community/lanzaboote#84]
Pretty much boils down to just not touching the graphics at all.
When nobody draws over the BGRT (or draws things at all), plymouth should be able to pick the logo up up in initrd ;)

**Comment by RaitoBezarius** [comment]
> Pretty much boils down to just not touching the graphics at all. When nobody draws over the BGRT (or draws things at all), plymouth should be able to pick the logo up up in initrd ;)

Good point, am I right thinking this requires honoring `quiet` in command line or?

**Comment by dasJ** [comment]
I would have expected the tool to be rebuilt but parsing the cmdline is a lot cleaner of course.

While we parse `quiet`, why not parse `loglevel=` as well and hook that up to `log::set_boxed_logger` and use the log macros rather than just printing? That would allow to add debug output aiding in development without manually adding print instructions.

**Comment by nikstur** [comment]
Am I right that this is an issue in the stub? I.e. the output of the stub draws over something? Or is the issue the output of `lzbt`? We already have a ticket for configurable verbosity in `lzbt`'s output: #73

**Comment by dasJ** [comment]
This is about the stub output

**Comment by nikstur** [comment]
I was just a little confused, because you used the term "tool" with which we usually refer to `lzbt` :)
