### ISSUE TITLE
fwupd support

### ISSUE THREAD

**Issue by dasJ** [nix-community/lanzaboote#85]
Probably a niche feature, but it'd be nice to have fwupd work out of the box.
It looks like all we have to do is make it sign its efi file [source](https://wiki.archlinux.org/title/fwupd#Secure_Boot) by doing:
> and add the file to the EXTRA_SIGN list in /etc/sbupdate.conf. 

Not 100% sure though, I haven't looked at this any further and I just did my updates before switching to lanzaboote ;)

**Comment by RaitoBezarius** [comment]
Not niche at all to me. It's important for me that people can actually use `fwupd` more or less out of the box with SecureBoot.

**Comment by nikstur** [comment]
This was resolved in #131
