### ISSUE TITLE
bzImage.efi is not signed

### ISSUE THREAD

**Issue by tmarkov** [nix-community/lanzaboote#92]
I just installed `lanzaboote`, deleted everything in `/boot`, and then rebuilt and reinstalled the bootloader.

Unfortunately, `sbctl verify` prints `✗ /boot/EFI/nixos/3h0yzc1r0h8hf4a43lz5plfvvfmj9q3q-linux-6.1.6-bzImage.efi is not signed`. I don't think this is #39, since I tried deleting everything in `/boot` twice and `nix-collect-garbage -d`, and the issue persists.

**Comment by RaitoBezarius** [comment]
Do you have the log of the `lanzaboote` when doing `nixos-rebuild switch`? So we can see if this is a skipping or not?

**Comment by RaitoBezarius** [comment]
(also, which revision are you running?)

**Comment by blitz** [comment]
Since today the kernel is not signed anymore. We need to update the docs.

**Comment by RaitoBezarius** [comment]
I realized indeed this does not mean the boot was failing. :D

**Comment by mrityunjaygr8** [comment]
> I realized indeed this does not mean the boot was failing. :D

does this mean that even with file not being signed, the system will still boot with secure boot enabled?

**Comment by RaitoBezarius** [comment]
> > I realized indeed this does not mean the boot was failing. :D
> 
> does this mean that even with file not being signed, the system will still boot with secure boot enabled?

Yes, but it's not breaking SecureBoot chain of trust :P.

Due to #65, we decided of removing SecureBoot signature on kernels and embed the kernel's hash in the stub which is signed by SecureBoot.

This prevents someone stealing that signed kernel to boot an untrusted initrd.
